### PR TITLE
Use 5 columns for articles and expand to fill window

### PR DESCRIPTION
**Pull request by creitz**

### CODE REVIEW

**Comment by stevemar** [comment]
@creitz please justify the change in the commit message. Upon reviewing it seems this is less helpful, since we're going from sorted news articles to random (why do this in the first place?).

**Comment by creitz** [comment]
Sure, sorry I should have added that. Because of the way the columns are layed out, after a while of trying it has proved very difficult to arrange them in the correct order. Because the articles are layed out in columns, rather than rows, the articles are really being arranged as such:

1 5
2 6
3 7
4 8

That part would not be a problem because I can rearrange the array accordingly to have them still be rendered in the correct order, but because the articles are not a consistent height, the columns don't always get rendered with the same number of items, so you can get something like this:

1 4
2 5
""6
3 7

where 3 would fill that space. But, the articles were sorted such that the articles at the bottom (4 and 8 in the first example) were the oldest. Now, however, article 4 (which should be the oldest and at the bottom) is at the top. With the rest of the articles sorted, to me this seemed like a blatant bug that I did not want to have for the demo. Since I tried for a while to fix it and time is short, I decided on this bandaid solution and possibly explaining that sorting is a future work item. If you disagree, though, I can revert.

**Comment by creitz** [comment]
Filling the space and using more columns though I believe is a good change.

**Comment by stevemar** [comment]
@creitz no need to revert, the change makes sense. just needed to make things more clearly for history.

**Pull request merged**
