### PR TITLE
Add a Web Interface

### PR DESCRIPTION
**Pull request by creitz**
Begin creating user web page. Node + express backend, angular frontend

### CODE REVIEW

**Comment by stevemar** [comment]
@creitz thanks for pushing up this PR!

I asked @rhagarty to review, he's the UI expert of the team. Anyway you can attach a screenshot? A picture is worth a thousand words and all that.

**Comment by creitz** [comment]
It is currently deployed at https://watson-stock-advisor.mybluemix.net/ . I'm sure @rhagarty will have a good amount of feedback, but please keep in mind this is just a starting point. There is plenty to be cleaned up, I know :)

**Comment by stevemar** [comment]
@creitz looks good so far! a fantastic first pass! 

A few comments:
* The companies should be selectable, and the graph should refresh
* Maybe a new text area to show some of the news articles
* Rename "Search" to "Filter"
* New box for actually searching a new company

These can all certainly be added in another PR BTW!

Adding a screenshot for completeness 
screen shot 2018-01-22 at 2 35 57 pm

**Review by rhagarty — APPROVED** [review]
Looks great! You guys are making good progress.

I've very little Angular experience, so I can't help much with that. But I do have a couple of thoughts:
1) you need to document the code better. A header for each function would be great. What does it do along with param descriptions.
2) need to add license tags on all source files. See example here - https://github.com/IBM/watson-discovery-ui/blob/master/src/TrendChart/index.js
3) would be nice if you provided a structure document that details what lives where. Great help to those who wish to review or add code. Something like this - https://github.com/IBM/watson-discovery-ui/blob/master/DEVELOPING.md
4) On a related note, looks like you are ready to add a nice architecture diagram to show how all the pieces fit together.
5) it's not too early to start thinking about adding some unit tests.
6) can you change the 'update' directory name? Something like 'server' or 'backend' would be more appropriate.
7) for the app itself, not sure about the value of the sentiment chart. I think it would more interesting to show a trend chart that graphs the sentiment of one stock over time. Or graph all selected stocks together. 
8) instead of just showing 'pos'/'neg' for sentiment, how about showing the actual score with an arrow. Score can be in green or red (reflective pos or neg), and an up/down arrow to indicate direction from previous score. 

Note that 7 & 8 are just suggestions. I know you guys are pressed for time.

**Comment by creitz** [comment]
Thanks for the feedback. Per each of your points: 

1 & 2) Will do
3) Should be easy with the tree tool :)
4 & 5) OK
6) I'm working on combining the update and web dirs in another branch...doesn't make sense to have 2 servers if we want easy example deployment
7) A graph is in the works, it's currently commented out.
8) Also planned.

Thanks!

**Pull request merged**
